FROM mrik974/nonroot-moodle:3.6.4-fr
LABEL description="This is an image of a Moodle runtime made for running on non root environments like Openshift with Moosh installed"

USER root

RUN apt-get -qq install git \
    && curl https://getcomposer.org/installer -o composer-install.php \
    && php composer-install.php --install-dir=/usr/local/bin --filename=composer \
    && git clone git://github.com/tmuras/moosh.git \
    && cd moosh \
    && /usr/local/bin/composer install \ 
    && ln -s $PWD/moosh.php /usr/local/bin/moosh \
    && mkdir /var/www/.moosh \
    && chown -R www-data:www-data /var/www/.moosh \
    && chmod -R 777 /var/www/.moosh

USER www-data

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["apachectl", "-e", "info", "-D", "FOREGROUND"]
